<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AssemblyName>PGame-TSManager</AssemblyName>
    <RootNamespace>PGameTSManager</RootNamespace>
    <AssemblyTitle>PGame-TSManager</AssemblyTitle>
    <Product>PGame-TSManager</Product>
    <Version>1.1.0</Version>
    <ApplicationIcon>PGame-TSManager.ico</ApplicationIcon>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="PGame-TSManager.ico" />
    <None Update="Plugins\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Compile Include="..\TerrariaServerAPI\TerrariaServerAPI\ServerConfig.cs" />
  </ItemGroup>

</Project>